/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ErrorDisplay: typeof import('./src/components/ErrorDisplay.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}
